### ISSUE TITLE
sonar-xml plugin 2.0.1.2020

### ISSUE THREAD

**Issue by JavaJimFl** [ntiss/sonar-apigee-plugin#22]
Good Morning,

SonarSource has released a new major version of the sonar-xml plugin.   While it isn't in the marketplace yet, the API has changed so much I won't be able to upgrade my server for fear of breaking the current version of the sonar-apigee plugin when it becomes available.

Could you please take a look at the new plugin and let me know what you think?

Thanks!

**Comment by ntiss** [comment]
Hi, 
Thank you for the feedback. I'll take a look at this when I have some time.

**Comment by ntiss** [comment]
Hi @JavaJimFl 
I'm currently working on upgrading my plugin. You're right, there are a lot of changes in the plugin API.
I'm only discovering the breaking changes. I don't know when I'll finish but I hope that it will be before the releasing of the new Sonar-XML in the marketplace.
Regards.

**Comment by JavaJimFl** [comment]
Just saw this reply yesterday.  If you need help with anything, please let me know.

**Comment by ntiss** [comment]
Hi @JavaJimFl 
Thanks for your proposition. Much appreciated.
Fortunaltely, I've almost finished to refactor the plugin. I'm completing the very latest tests.
If you want to beta-test, try it here : https://github.com/CreditMutuelArkea/sonar-apigee-plugin/releases/tag/2.0.0-alpha.0
(official RC will be announced next week on SonarQube forum)

**Comment by JavaJimFl** [comment]
Good Morning,

I can't test because I can't upgrade my server past v7.5 because SonarSource broke several other plugins we use.  I can take a look at the changes though. 

Thanks for taking the time to update the plugin.

**Comment by ntiss** [comment]
No problem.
I've published the RC0 for feedback : https://community.sonarsource.com/t/rff-sonar-apigee-plugin-2-0-0/8338
The final release will be available in the marketplace soon after the end of the week.
The new release will be compatible with SonarQube 6.7 to 7.7 with sonar-xml plugin in 2.0.1 version.

**Comment by ntiss** [comment]
Hi @JavaJimFl 
This issue is now closed. Fix is in the release 2.0.0 : https://github.com/CreditMutuelArkea/sonar-apigee-plugin/releases/tag/v2.0.0
Available in the SonarQube Marketplace.
Thanks for reporting.
