### ISSUE TITLE
sonar-xml plugin 2.0.1.2020 changes how violations are displayed

### ISSUE THREAD

**Issue by JavaJimFl** [ntiss/sonar-apigee-plugin#26]
Good Afternoon,

I upgraded a company-specific Apigee plugin after you completed your changes.  When I was finished, all my unit tests still passed, yet the way the violations are displayed on the server didn't match the way they had been previously displayed.  Long story short, SonarSource changed the way violations are associated with an element.  Instead of using the opening tag as the basis for the issue associated with an element/node it now uses the closing tag.  That means, among other things, any errors associated with the root element of a XML will now show the entire document as having an error.  It's really ugly, and SonarSource has refused to change their code in any way.

To make the issues display the way they used to, you have pass the node to one of a number of convenience methods in the `XmlFile` class to get a `XmlTextRange` instance that you can in turn pass to the  `SonarXmlCheck.reportIssue(XmlTextRange, String)` method.

I just wanted to give you a heads-up and save you from having to troubleshoot the problem from scratch.

**Comment by ntiss** [comment]
Hi @JavaJimFl 
Yes, I agree with you, the new highlighting system in SonarXML is a bit ugly compared to the old one.
But it can be fine tuned. This is what I've done for the rule "UnknownResourceFlowCheck" : it highlights the closing tag for </Flows>.

On which rules would you like to have a better highlighting for the violations ?

**Comment by JavaJimFl** [comment]
That's totally up to you.  The worst looking errors are the ones on the root element of the document, which highlights the entire document as an issue.  I'd think you'd want to address those if nothing else.

**Comment by ntiss** [comment]
@JavaJimFl  Yes, this is what I try to avoid as much as possible. I only place the issue on the root element if I fail to find a better place. This is the worst case.
Don't hesitate to suggest me which rules you'd like to be be improved.
Can I close this issue? Is it ok for you?

**Comment by JavaJimFl** [comment]
Absolutely, it was just a heads-up.  Thanks for taking the time to listen!
